CONSOLE_NONE=0;CONSOLE_ERROR=1;CONSOLE_WARN=2;CONSOLE_INFO=3;CONSOLE_DEBUG=4;CONSOLE_LOG=5;CONSOLE_ALL=9;var R=function(a){for(var b=CONSOLE_NONE,e=a.console,d=/(iphone|ipad|ipod|android)/.test(navigator.userAgent.toLowerCase()),c={},j=[],i,g,m=["error","warn","info","debug","log"],k="assert clear count dir dirxml exception group groupCollapsed groupEnd profile profileEnd table time timeEnd trace".split(" "),
n=k.length;--n>=0;)(function(f){c[f]=function(){b!==0&&e&&e[f]&&e[f].apply(e,arguments)}})(k[n]);for(n=m.length;--n>=0;)(function(f,t){c[t]=function(){j.push([t].concat(Array.prototype.slice.call(arguments)));if(i&&(g||!e||!e.log))i.apply(a,arguments);if((b>0?b>f:m.length+b<=f)&&e)try{e[t]?d?e[t].call(e,arguments.join(" ")):e[t].apply(e,arguments):d?e.log.call(e,arguments.join(" ")):e.log.apply(e,arguments)}catch(E){e.log(Array.prototype.slice.call(arguments).join(" "))}}})(n,m[n]);c.getLogs=function(){return j};
c.setCallback=function(f,t){i=f;g=!!t};c.setLevel=function(f){b=Number(f)};return c}(window);window.debug=R;(function(a){function b(Y,U){var Q=/^\w+\:\/\//,fa;if(typeof Y!=c)Y="";if(typeof U!=c)U="";fa=(Q.test(Y)?"":U)+Y;return(Q.test(fa)?"":fa.charAt(0)==="/"?ca:ba)+fa}function e(Y,U){function Q(C,N){if(C[m]&&C[m]!==E&&C[m]!=="loaded"||N[u])return s;C[D]=C[o]=r;return v}function fa(C,N,z){if((z=!!z)||Q(C,N)){N[u]=v;for(var L in za)if(za[F](L)&&!za[L][u])return;
Db=v;na()}}function ma(C){if(J.call(C[n])===p){C[n]();C[n]=r}}function ga(C,N){if(Q(C,N)){N[k]=v;X(function(){H[N[w]].removeChild(C);ma(N)},0)}}function S(C,N){if(C[m]===4){C[o]=l;N[k]=v;X(function(){ma(N)},0)}}function Nb(C,N,z,L,qa,Aa){var Ba=C[w];X(function(){if("item"in H[Ba]){if(!H[Ba][0]){X(arguments.callee,25);return}H[Ba]=H[Ba][0]}var Ca=P.createElement(g);if(typeof z==c)Ca.type=z;if(typeof L==c)Ca.charset=L;if(J.call(qa)===p){Ca[D]=Ca[o]=function(){qa(Ca,C)};Ca.src=N;if(aa)Ca.async=s}H[Ba].insertBefore(Ca,
Ba===j?H[Ba].firstChild:r);if(typeof Aa==c){Ca.text=Aa;fa(Ca,C,v)}},0)}function cc(C,N,z,L){K[C[f]]=v;Nb(C,N,z,L,fa)}function ra(C,N,z,L){var qa=arguments;if(Ia&&C[k]==r){C[k]=s;Nb(C,N,h,L,ga)}else if(!Ia&&C[k]!=r&&!C[k])C[n]=function(){ra.apply(r,qa)};else Ia||cc.apply(r,qa)}function ya(C,N,z,L){var qa=arguments,Aa;if(Ia&&C[k]==r){C[k]=s;Aa=C.xhr=da?new da("Microsoft.XMLHTTP"):new a.XMLHttpRequest;Aa[o]=function(){S(Aa,C)};Aa.open("GET",N);Aa.send("")}else if(!Ia&&C[k]!=r&&!C[k])C[n]=function(){ya.apply(r,
qa)};else if(!Ia){K[C[f]]=v;Nb(C,N,z,L,r,C.xhr.responseText);C.xhr=r}}function sa(C){if(C.allowDup==r)C.allowDup=U.dupe;var N=C.type,z=C.charset,L=C.allowDup;C=b(C.src,Ja);var qa=b(C).indexOf(ca)===0;if(typeof z!=c)z=r;L=!!L;if(L=!L){if(!(L=K[C]!=r)){if(!(L=Ia&&za[C]))a:{for(var Aa=-1;L=I[++Aa];)if(typeof L.src==c&&C===b(L.src)&&L.type!==h){L=v;break a}L=s}L=L}L=L}if(L)za[C]!=r&&za[C][k]&&!za[C][u]&&qa&&fa(r,za[C],v);else{if(za[C]==r)za[C]={};L=za[C];if(L[w]==r)L[w]=Ob;L[u]=s;L[f]=C;Pb=v;if(!wb&&
dc&&qa)ya(L,C,N,z);else!wb&&ec?ra(L,C,N,z):cc(L,C,N,z)}}function Ya(C){Y&&!wb&&ta.push(C);if(!Y||Ka)C()}function xb(C){var N=[],z;for(z=-1;++z<C.length;)if(J.call(C[z])===y)N=N.concat(xb(C[z]));else N[N.length]=C[z];return N}Y=!!Y;if(U==r)U=O;var Db=s,Ka=Y&&U[t],ec=Ka&&U.cache,wb=Ka&&U.order,dc=Ka&&U.xhr,Qb=U[B],Ob=U.which,Ja=U.base,na=l,Pb=s,Eb,Ia=v,za={},ta=[],q=r;Ka=ec||dc||wb;Eb={script:function(){A(q);var C=xb(arguments),N=Eb,z;if(Qb)for(z=-1;++z<C.length;){if(z===0)Ya(function(){sa(typeof C[0]==
c?{src:C[0]}:C[0])});else N=N.script(C[z]);N=N.wait()}else Ya(function(){for(z=-1;++z<C.length;)sa(typeof C[z]==c?{src:C[z]}:C[z])});q=X(function(){Ia=s},5);return N},wait:function(C){A(q);Ia=s;J.call(C)===p||(C=l);var N=e(v,U),z=N.trigger,L=function(){try{C()}catch(Aa){}z()};delete N.trigger;var qa=function(){if(Pb&&!Db)na=L;else L()};Y&&!Pb?ta.push(qa):Ya(qa);return N}};if(Y)Eb.trigger=function(){for(var C,N=-1;C=ta[++N];)C();ta=[]};return Eb}function d(Y){var U,Q={},fa={UseCachePreload:"cache",
UseLocalXHR:"xhr",UsePreloading:t,AlwaysPreserveOrder:B,AllowDuplicates:"dupe"},ma={AppendTo:w,BasePath:"base"};for(U in fa)ma[U]=fa[U];Q.order=!!O.order;for(U in ma)if(ma[F](U)&&O[ma[U]]!=r)Q[ma[U]]=Y[U]!=r?Y[U]:O[ma[U]];for(U in fa)if(fa[F](U))Q[fa[U]]=!!Q[fa[U]];if(!Q[t])Q.cache=Q.order=Q.xhr=s;Q.which=Q.which===j||Q.which===i?Q.which:j;return Q}var c="string",j="head",i="body",g="script",m="readyState",k="preloaddone",n="loadtrigger",f="srcuri",t="preload",E="complete",u="done",w="which",B="preserve",
o="onreadystatechange",D="onload",F="hasOwnProperty",h="script/cache",p="[object Function]",y="[object Array]",r=null,v=true,s=false,P=a.document,da=a.ActiveXObject,X=a.setTimeout,A=a.clearTimeout,J=Object.prototype.toString,l=function(){},H={},K={},ba=/^[^?#]*\//.exec(a.location.href)[0],ca=/^\w+\:\/\/\/?[^\/]+/.exec(ba)[0],I=P.getElementsByTagName(g),W=a.opera&&J.call(a.opera)=="[object Opera]",M="MozAppearance"in P.documentElement.style,aa=P.createElement(g).async===true,O={cache:!(M||W),order:M||
W||aa,xhr:v,dupe:v,base:"",which:j};O[B]=s;O[t]=v;H[j]=P.head||P.getElementsByTagName(j);H[i]=P.getElementsByTagName(i);a.$LAB={setGlobalDefaults:function(Y){O=d(Y)},setOptions:function(Y){return e(s,d(Y))},script:function(){return e().script.apply(r,arguments)},wait:function(){return e().wait.apply(r,arguments)}};(function(Y,U,Q){if(P[m]==r&&P[Y]){P[m]="loading";P[Y](U,Q=function(){P.removeEventListener(U,Q,s);P[m]=E},s)}})("addEventListener","DOMContentLoaded")})(window);(function(){var a=false,b=/xyz/.test(function(){})?/\b_super\b/:/.*/;this.MingClass=function(){};MingClass.extend=function(e){function d(){!a&&this.init&&this.init.apply(this,arguments)}var c=this.prototype;a=true;var j=new this;a=false;for(var i in e)j[i]=typeof e[i]=="function"&&typeof c[i]=="function"&&b.test(e[i])?function(g,m){return function(){var k=this._super;this._super=c[g];var n=m.apply(this,arguments);
this._super=k;return n}}(i,e[i]):e[i];d.prototype=j;d.constructor=d;d.extend=arguments.callee;return d}})();XHR=function(){function a(e){try{return JSON.parse(e)}catch(d){return e}}function b(e,d,c,j,i,g){var m=/^(\w+:)?\/\/([^\/?#]+)/.exec(d);m=m&&(m[1]&&m[1].toLowerCase()!==location.protocol||m[2].toLowerCase()!==location.host);var k=window.XDomainRequest&&m?new XDomainRequest:window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(g==="script"&&e==="GET"&&
m){var n=document.getElementsByTagName("head")[0]||document.documentElement,f=document.createElement("script"),t=false;f.src=d;f.onload=f.onreadystatechange=function(){if(!t&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){t=true;f.onload=f.onreadystatechange=null;n&&f.parentNode&&n.removeChild(f)}};n.insertBefore(f,n.firstChild);return true}k.open(e,d,!!j);if(k.setRequestHeader){k.setRequestHeader("Content-Type","application/x-www-form-urlencoded");m||k.setRequestHeader("X-Requested-With",
"XMLHttpRequest")}if(i)k.withCredentials=true;if(j)k.onreadystatechange=function(){k.readyState===4&&j.call(k,a(k.responseText),k.status)};k.send(c);return j?true:a(k.responseText)}this.get=function(e,d){return b("GET",e,null,d)};this.getWithCredentials=function(e,d){return b("GET",e,null,d,true)};this.getJson=function(e,d){return b("GET",e,null,null,d,"script")};this.post=function(e,d,c){return b("POST",e,d,c)};this.postWithCredentials=function(e,d,c){return b("POST",e,d,c,true)};this.request=b};
window.XHR=XHR;ICanHas=function(a,b){return{cors:function(){var e=b.XDomainRequest||b.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest;if(e){e=new Boolean(e);e.withCredentials=!window.XDomainRequest}return e}(),orientation:window.orientation!==void 0,touch:"ontouchstart"in b,video:function(){var e=a.createElement("video"),d=!!e.canPlayType;if(d){d=new Boolean(d);d.vp6=e.canPlayType('video/x-flv; codecs="vp6"')||
false;d.vp8=e.canPlayType('video/webm; codecs="vp8,vorbis"')||false;d.h264=navigator.userAgent.toLowerCase().search("android")>-1?"probably":e.canPlayType('video/mp4; codecs="avc1.42E01E"')||e.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')||false}return d}()}}(document,window);FlashDetect=function(){var a=navigator,b=false,e=0,d=0,c=0,j=null,i=null;if(a.plugins&&a.plugins.length){if((a=a.plugins["Shockwave Flash"])&&a.description){j=a.description;b=true}}else if(a.mimeTypes&&a.mimeTypes.length){if((a=a.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin)b=true}else try{j=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version");
b=true}catch(g){}if(j){i=j.replace(/\D+/g,".").replace(/^\./,"");a=i.split(".");e=parseInt(a[0],10);d=parseInt(a[1],10);c=parseInt(a[2],10)}return{installed:b,raw:j,version:i,major:e,minor:d,revision:c,versionAtLeast:function(m,k,n){m=m||10;k=k||0;n=n||0;var f=[e,d,c],t=arguments,E=Math.min(f.length,t.length),u;for(u=0;u<E;u++)if(f[u]>=t[u]){if(!(u+1<E&&f[u]===t[u]))return true}else return false}}}();$m={};(function(a){function b(h,p,y){if(a.type(y)!=="array"||y===m)y=[y];for(var r=0,v=y.length;r<v;r++)y[r][h]||(y[r][h]=p);a[h]=function(){var s=Array.prototype.slice.call(arguments),P=s.shift();return p.apply(P,s)}}function e(h,p,y,r){y[h]=p;r.push(h);r.length>1E3&&delete y[r.shift()];return p}function d(h,p){if(h in p)return p[h];return false}function c(){var h=this.valueOf();return h<0?~~h-1:~~h}function j(h,p){return this<p?h>this?h:this:
p}function i(h,p){var y=this.valueOf()+"";return Array(h-y.length+1).join(p||"0")+y}if(!window.Element)window.Element={};for(var g=document,m=Array.prototype,k=!window.HTMLElement?{}:HTMLElement.prototype,n=!window.NodeList?{}:NodeList.prototype,f=Number.prototype,t=String.prototype,E=window,u={},w=[],B="Boolean Number String Function Array Date RegExp Object".split(" "),o=[],D=0,F=B.length;D<F;D++)o["[object "+B[D]+"]"]=B[D].toLowerCase();a.type=function(h){return h==null?String(h):o[Object.prototype.toString.call(h)]||
"object"};a.isArray=function(h){return a.type(h)==="array"};a.emptyFunction=function(){};a.clone=function(h){var p=a.isArray(h)?[]:{};for(D in h)if(D!=="clone")p[D]=h[D]&&a.type(h[D])==="object"?a.clone(h[D]):h[D];return p};a.addEventListener=function(h,p,y){window.addEventListener?h.addEventListener(p,y,false):h.attachEvent("on"+p,y)};a.removeEventListener=function(h,p,y){window.removeEventListener?h.removeEventListener(p,y,false):h.detachEvent("on"+p,y)};a.findKey=function(h,p){for(var y in p)if(p.hasOwnProperty(y)&&
p[y]===h)return y;return false};a.fibonacci=function(h){var p=Math.sqrt(5);return(1/p*Math.pow((1+p)/2,h)-1/p*Math.pow((1-p)/2,h)).round()};a.withinElement=function(h,p){var y=p.relatedTarget;try{if(y&&y!==document&&!y.parentNode)return true;for(;y&&y!==h;)y=y.parentNode;if(y!==h)return false}catch(r){}return true};b("abs",function(){var h=this.valueOf();return h<0?-h:h},f);b("addClass",function(h){if(this.length&&this.forEach)this.forEach(function(p){a.addClass(p,h)});else if(!a.hasClass(this,h))this.className=
this.className.split(" ").concat(h).unique().join(" ").trim();return this},[k,n]);b("attr",function(h,p){if(a.type(h)==="object"){for(prop in h)this.setAttribute(prop,h[prop]);return this}if(p===void 0)return this.getAttribute(h);p===null||p===""?this.removeAttribute(h):this.setAttribute(h,p);return this},k);b("ceil",function(){return c.call(this.valueOf()+1)},f);b("clamp",function(h,p,y){function r(){if(checkCount>200)return false;if(v.innerText!=h||v[property]==0){checkCount++;setTimeout(r,1)}else a:if(!(v[property]<=
y)){for(;v[property]>y;){v.innerText=v.innerText.substr(0,v.innerText.length-1);if(v.innerText==""||v.innerText.length==0)break a}v.innerText=v.innerText.substr(0,v.innerText.length-3)+"..."}}var v=this;v.innerHTML=h;property=p=="height"?"clientHeight":"clientWidth";checkCount=0;r();return v},k);b("clear",function(){this.childNodes.forEach(function(h){h.remove&&h.remove()});return this},k);b("computeStyle",function(h){if(!E.getComputedStyle)E.getComputedStyle=function(p){this.el=p;this.getPropertyValue=
function(y){var r=/(\-([a-z]){1})/g;if(y=="float")y="styleFloat";if(r.test(y))y=y.replace(r,function(v,s,P){return P.toUpperCase()});return p.currentStyle&&p.currentStyle[y]?p.currentStyle[y]:null};return this};return E.getComputedStyle(this,null).getPropertyValue(h)},k);b("contains",function(h){return this.indexOf(h)!==-1},[m,t]);b("css",function(h,p){if(a.type(h)==="object"){for(prop in h)this.style[prop]=h[prop];return this}if(p===void 0)return this.style[h];this.style[h]=p===null||p===""?"":p;
return this},k);b("floor",c,f);b("forEach",function(h,p){if(a.type(h)==="function")for(var y=this.length>>>0,r=0;r<y;r++)r in this&&h.call(p,this[r],r,this)},[m,n]);b("getElementsByClassName",function(h){var p=[],y=0,r,v,s;if(document.evaluate){r=".//*[contains(concat(' ', @class, ' '), ' "+h+" ')]";for(v=document.evaluate(r,this,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);s=v.snapshotItem(y++);)p[p.length]=s}else{r=RegExp("(^|\\s)"+h+"(\\s|$)");v=this.getElementsByTagName("*");y=0;for(var P=
v.length;y<P;y++){s=v[y];if(s.className===h||r.test(s.className))p[p.length]=s}}return p},g);b("hasAncestor",function(h){if(h===this)return true;for(var p=this.parentNode;p;){if(p===h)return true;p=p.parentNode}return false},k);b("hasClass",function(h){if(h.splice){for(var p=this.className.split(" "),y=0,r=p.length;y<r;y++)if(h.contains(p[y]))return true;return false}return RegExp("(?:^|\\s+)"+h+"(?:\\s+|$)").test(this.className)},k);b("hex2rgb",function(){if(cached=d(this,u))return cached;var h=
parseInt(this.replace("#",""),16);h=[(h&16711680)>>16,(h&65280)>>8,h&255];return e(this,"rgb("+h.join(",")+")",u,w)},t);b("html",function(h){if(h===void 0)return this.innerHTML;this.innerHTML=h;return this},k);b("indexOf",function(h){for(var p=0,y=this.length;p<y;p++)if(this[p]==h)return p;return-1},m);b("innerHeight",function(){for(var h=0,p,y=0,r=this.childNodes.length;y<r;y++){p=this.childNodes[y];if(p.style)h+=p.clientHeight+(a.toInt(a.computeStyle(p,"margin-top"),10)||0)+(a.toInt(a.computeStyle(p,
"margin-bottom",10))||0)}return h},k);b("limit",j,f);b("map",function(h,p){for(var y=this.length>>>0,r=Array(y),v=0;v<y;v++)if(v in this)r[v]=h.call(p,this[v],v,this);return r},m);b("max",function(){return Math.max.apply(Math,this)},m);b("min",function(){return Math.min.apply(Math,this)},m);b("pad",i,[t,f]);b("position",function(){var h=0,p=0,y=this;if(y.offsetParent){do{h+=y.offsetLeft;p+=y.offsetTop}while(y=y.offsetParent)}return{x:h,y:p}},k);b("prependChild",function(h){return this.insertBefore(h,
this.firstChild)},k);b("q",function(h){return this.querySelector(h)},[g,k]);b("qa",function(h){return this.querySelectorAll(h)},[g,k]);b("remove",function(){if(this.length)this.forEach(function(h){h.parentNode&&h.parentNode.removeChild(h)});else this.parentNode&&this.parentNode.removeChild(this)},[k,n]);b("removeClass",function(h){if(this.length&&this.forEach)this.forEach(function(p){a.removeClass(p,h)});else if(a.hasClass(this,h))this.className=this.className.replace(RegExp("(?:^|\\s+)"+h+"(?:\\s+|$)",
"g")," ").trim();return this},[k,n]);b("rgb2hex",function(){if(cached=d(this,u))return cached;var h=this.match(/\d{1,3}/g).slice(0,3);h=h.map(function(p){return i.call(j.call(parseInt(p,10),0,255).toString(16),2)});return e(this,h.join(""),u,w)},t);b("round",function(){return c.call(this.valueOf()+0.5)},f);b("toInt",function(h){return parseInt(this.valueOf?this.valueOf():this,h||10)},[t,f]);b("toFloat",function(h){return parseFloat(this.valueOf(),h||10)},[t,f]);b("trim",function(){return this.replace(/^\s\s*/,
"").replace(/\s\s*$/,"")},t);b("ucfirst",function(){return this.charAt(0).toUpperCase()+this.slice(1)},t);b("unique",function(){var h=[],p=0,y=this.length;a:for(;p<y;p++){for(var r=0,v=h.length;r<v;r++)if(h[r]===this[p])continue a;h[h.length]=this[p]}return h},m);b("wrap",function(h,p){var y=this,r=a.addClass(document.createElement(h),p||"");y.length||(y=Array(this));y.forEach(function(v,s){s===0&&v.parentNode.replaceChild(r,v);r.appendChild(v)});return r},[k,n])})($m);EventManager=function(){function a(d){if(!b[d]){var c=document.createElement("a");c.id="Event:"+d;e.appendChild(c);b[d]=c}return b[d]}var b={},e=document.createElement("div");e.id="events"+(new Date).getTime();document.body.appendChild(e);this.bind=function(d,c){var j=a(d);window.addEventListener?j.addEventListener("click",
c,false):j.attachEvent("onclick",c);return this};this.unbind=function(d,c){var j=a(d);window.removeEventListener?j.removeEventListener("click",c,false):j.detachEvent("onclick",c);return this};this.fire=function(d,c){var j,i=a(d);if(document.createEvent){j=document.createEvent("HTMLEvents");j.initEvent("click",false,true);j.name=d;j.data=c;return i.dispatchEvent(j)}else{try{c=JSON.stringify(c)}catch(g){}j=document.createEventObject();j.name=d;j.data=c;return i.fireEvent("onclick",j)}}};window.EventManager=
EventManager;var yb="ming",zb="moogaloop",lc="noplayer",uc="nomobile",gb="mobile",kc="touch",Mb="desktop",Hc="html",Gc="flash",ia="noplayer",xa="hd",Ua="sd",Ra="mobile",Jc=[xa,Ua,Ra],jd="pl_volume",Dc="hd_preference",Ib="onwebkittransitionend"in window?"webkitTransitionEnd":"transitionEnd",Hb=8,kd=250,Ec=140,Fc=200,
ld=265;ia=200;var Tb=7,nc=1.5,Kc=2E3,Ic=1500,Oa=1,Sa=2,Jb=3,ka=4,pa=5,Ma=6,$b=7,Bb=8,kb=9,Lc=10,Mc=11,Nc=12,Oc=13,Ub=14,Lb=15,qb=16,Pc=17,qc=18,rc=19,bc=20,Qc=21,sc=22,tc=23,ha=24,va=25,jb=26,$a=27,Zb=28,la=29,Kb=30,Rc=31,Ea=32,cb=33,db=34,Na=35,nb="loadProgress",ob="playProgress",mb="play",lb="pause",Ab="finish",pb="seek",vb="ready",hd="error",mc="addEventListener()",vc="removeEventListener()",sb="play()",rb="pause()",tb="seekTo()",ub="unload()",Va="setColor()",eb="setLoop()",fb="setVolume()",Ga=
"getDuration()",Fa="getCurrentTime()",Wa="getVolume()",wc="getColor()",Cb="getLoop()",xc="getVideoUrl()",yc="getVideoEmbedCode()",ab="getVideoWidth()",bb="getVideoHeight()",Pa="paused()",La="a",ac="ab",Rb="ap",ic="ar",V="bk",Z="s",pc="be",Yb="ae",dd="i",ed="q",fd="r",gd="s";ia="ag";ia="f";ia="c";ia="g";var Sc="ax",md="o";ia="al";ia="ck";var Fb="x",Gb="w",hb="aa",Za="p",Qa="k",Sb="v",Ta="j",hc="bh",jc="bb",$c="co",ad="z",gc="bz",bd="as",ib="by",fc="cx",nd="ay",wa="b",zc="h",Ac="an";ia="ca";var Tc=
"i",od="bm",pd="az",Vb="ak";ia="cy";var qd="af",rd="m";ia="at";Za="p";var sd="am",td="aj",Ha="e",ua="d",Wb="ah",Xb="ch",oc="bt",Uc="bi",ud="q",vd="videos",wd="au",Cc="bc",Xa="r",xd="bl",Vc="bj",ja="l",Bc="n",yd="bo",Wc="ai",zd="y";ia="dj";var Xc="ci",Yc="bn",Ad="cb",Zc="bv";ia="k";var cd="bs",id="ce";if(window.$){$=$;$$=$$}var x=MingClass.extend({init:function(a,b,e){function d(){if(!ICanHas.video)return false;if(m.ie)return false;if(m.safari&&m.safari<
4)return false;for(var k in c.config.video.files)if(ICanHas.video[k])return true;return false}var c=this,j=b.assets,i,g;i=navigator;g=i.userAgent.toLowerCase();i=i.platform.toLowerCase();var m={webkit:"webkitAppearance"in document.documentElement.style?parseFloat(g.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false,firefox:/firefox/.test(g)?g.replace(/^.*firefox\/(\d+\.\d+\.\d+).*$/,"$1"):false,safari:/safari/.test(g)?parseFloat(g.replace(/^.*version\/(\d+)\.(\d+)?.*$/,"$1.$2")):false,ie:navigator.appName==
"Microsoft Internet Explorer",opera:window.opera&&{}.toString.call(window.opera)=="[object Opera]"||false,win:i?/win/.test(i):/win/.test(g),mac:/mac/.test(i||g)?parseFloat(g.replace(/^.* ((\d+)(_|\.)?(\d+)?).*$/,"$2.$4")):false,linux:i?/linux/.test(i):/linux/.test(g),android:/android/.test(g)?parseFloat(g.replace(/^.* android (\d+)\.(\d+).*$/,"$1.$2")):false,playBook:/playbook/.test(g)};c.element=a;c.config=b.config;c.playerType=null;c.playerMode=null;c.playableFiles=null;c.thumbs=b.thumbs;c.api=
false;c.ua=m;c.uniqueId=b.uniqueId;x.cookieDomain=c.config.request.cookie_domain;c.playerMode=function(){if(c.playerMode)return c.playerMode;var k=Mb;if(Math.min(screen.width,screen.height)<=480||x.getCookie("test_mobiloop")=="1"||m.android&&m.android<3)k=gb;else if(ICanHas.orientation)k=kc;return k}();c.playableFiles=function(){var k=c.config.video,n=k.files,f={hd:false,sd:false,mobile:false};for(codec in n)if(ICanHas.video[codec]){if(c.playerMode===gb){if($m.contains(n[codec],Ra))f.mobile=codec;
else if(x.mobileCanPlaySD()&&$m.contains(n[codec],Ua))f.sd=codec;break}for(var t=0,E=n[codec].length;t<E;t++){var u=n[codec][t];if(u===xa&&!f.hd)f.hd=codec;else if(u===Ua&&!f.sd)f.sd=codec;else if(u===Ra&&!f.mobile)f.mobile=codec}}if(!c.config.security.hd_embed)f.hd=false;if(c.playerMode===kc)if(k.height*k.width>921600){R.info("Can't play HD version on iPad: too big");f.hd=false;c.config.video.hd=false}return f}();c.playerType=function(k){var n=lc;switch(k){case Gc:n=FlashDetect.installed&&FlashDetect.major>=
10?zb:d()?yb:n;break;case Hc:n=c.playerMode!==gb&&!c.playableFiles.hd&&!c.playableFiles.sd?FlashDetect.installed&&FlashDetect.major>=10?zb:c.playableFiles.mobile?yb:n:d()?yb:FlashDetect.installed&&FlashDetect.major>=10?zb:n;break}if(c.playerMode===gb&&!c.playableFiles.mobile){a:{k=c.config.video.files;for(codec in k)if($m.contains(k[codec],Ra)){k=true;break a}k=false}n=k?lc:x.mobileCanPlaySD()&&c.playableFiles.sd?yb:uc}return n}(c.config.user.preferences.html===1?Hc:Gc);g=c.playerType===zb?j.moogaloop:
j.ming[c.playerMode].js;i=c.playerType===zb?[]:j.ming[c.playerMode].css;R.info("Player Type:",c.playerType);R.info("Player Mode:",c.playerMode,Math.min(screen.width,screen.height));R.info("Screen Size:",screen.width,"x",screen.height);R.info("Can play:",ICanHas.video.h264?"h264":"");R.info("Playable Files:",c.playableFiles.hd?"hd":"",c.playableFiles.sd?"sd":"",c.playableFiles.mobile?"mobile":"");c.setThumb();$m.forEach(i,function(k){var n=document.createElement("link");$m.attr(n,{rel:"stylesheet",
href:j.css_path+k+(!j.cache?(k.indexOf("?")>-1?"&":"?")+(new Date).getTime():"")});document.getElementsByTagName("head")[0].appendChild(n)});i=$LAB.setOptions({AlwaysPreserveOrder:true,BasePath:j.js_path});j.cache||(g=$m.map(g,function(k){return k+(k.indexOf("?")>-1?"&":"?")+(new Date).getTime()}));i.script(g).wait(function(){c.api=new x.API(c.config);playerElement=a.getElementsByTagName("div")[0];$m.addClass(playerElement,c.playerType===zb?cd:La);c.player=new (c.playerType===zb?x.Moogaloop:c.playerType===
lc||c.playerType===uc?x.NoPlayer:x.Ming)(playerElement,b.options[c.playerType===uc?lc:c.playerType],c);e&&e.call(c)});R.info("Reticulating splines...")},getConfig:function(){return this.config},setConfig:function(a){this.config=a},setThumb:function(){var a=this.element.getElementsByTagName("div")[0].getElementsByTagName("div")[0],b=a.getAttribute("data-thumb"),e=this.thumbs[640];for(var d in this.thumbs)if(this.thumbs.hasOwnProperty(d))if(this.element.clientWidth>=d-100||this.element.clientWidth>=
940){e=this.thumbs[d];break}this.config.video.thumbnail=e;if(b!==e&&this.playerType===yb){if(this.config.embed.autoplay===0||this.playerMode!==Mb)a.style.backgroundImage="url("+e+")";a.setAttribute("data-thumb",e)}}});x.setCookie=function(a,b,e,d){var c=document.getElementById(dd),j="";e=e||87600;d=d||x.cookieDomain;if(c){document.getElementById(ed).value=a;document.getElementById(fd).value=b;document.getElementById(gd).value=e;window.addEventListener("message",function(i){i.data=="refresh"&&x.xhrRefresh()},
false);c.submit()}else{if(e){c=new Date;c.setTime(c.getTime()+e*60*60*1E3);j="; expires="+c.toGMTString()}d="; domain="+d;document.cookie=a+"="+b+j+"; path=/"+d}};x.getCookie=function(a){var b=document.cookie;a=a+"=";var e;if(b&&b!==""){b=document.cookie.split(";");for(var d=0,c=b.length;d<c;d++){e=b[d].trim();if(e.indexOf(a)===0)return unescape(e.substr(a.length))}}return null};x.eatCookie=function(a){document.cookie=a+"=; expires=Thu, 01-Jan-70 00:00:01 GMT;"};x.xhrRefresh=function(){var a;(new XHR).get(document.location.href,
function(b){a=document.getElementsByTagName("body")[0];a.innerHTML=b;$m.forEach(a.getElementsByTagName("script"),function(e){e.innerHTML&&(new Function(e.innerHTML)).call(window)})})};x.checkRatio=function(a,b,e){if(!b)return false;e=e.video.width/e.video.height;var d=a.clientWidth/a.clientHeight;if(Math.abs(e-d)<0.02){$m.removeClass(a,Fb);$m.removeClass(a,Gb)}else if(d>e){$m.removeClass(a,Gb);$m.addClass(a,Fb)}else{$m.removeClass(a,Fb);$m.addClass(a,Gb)}$m.removeClass(b,V)};x.mobileCanPlaySD=function(){return window.devicePixelRatio>=
2};if(!x.init)x.init={queue:[],loaderAdded:false,loader:function(){x.init.queue.length>0&&x.init.queue.shift()()}};window.Player=x;
x.Moogaloop=MingClass.extend({init:function(a,b,e){function d(l,H,K){R.info("url: ",l);var ba={server:o.request.vimeo_url,player_server:o.request.player_url,cdn_server:o.request.cdn_url,embed_location:o.request.referrer,force_embed:b.force_embed,force_info:b.force_info,moogaloop_type:J,js_api:1,js_getConfig:b.ref_id+".getConfig",js_setConfig:b.ref_id+".setConfig",clip_id:o.video.id,fullscreen:1},ca={id:H.id,name:H.id,styleclass:Z};if(D.ie)l+=(l.indexOf("?")>0?"&":"?")+"time="+(new Date).getTime();
for(attr in K)if(K.hasOwnProperty(attr))ba[attr]=K[attr];swfobject.embedSWF(l,H.id,"100%","100%","10.0.0","/assets/flash/expressInstall.swf",ba,{allowscriptaccess:"always",allowfullscreen:"true",scalemode:"noscale",quality:"high",wmode:"opaque",bgcolor:"#000000"},ca,function(I){if(D.safari&&D.win){R.debug("Removing invisible from swfobject");$m.removeClass(I.ref,Z)}D.android&&D.android<2.2&&$m.removeClass(I.ref,Z);setTimeout(function(){if($m.hasClass(H,Xa))return l.indexOf(y)===0?B.loverLoaded():
B.moogaloopLoaded();else if(A&&$m.hasClass(A,Z))return l.indexOf(y)===0?B.loverThumbLoaded(true):B.moogaloopThumbLoaded(true)},2E3)})}function c(){setTimeout(function(){p.fire(vb)},0)}function j(){var l="cover"+e.uniqueId;P=document.getElementById(l);if(!P){P=document.createElement("div");P.setAttribute("id",l);$m.addClass(P,id);a.appendChild(P)}d(y,P,{js_onLoad:b.ref_id+".player.loverLoaded",js_onThumbLoaded:b.ref_id+".player.loverThumbLoaded",js_setupMoog:b.ref_id+".player.loverInitiated"});o.embed.autoplay=
1}function i(){var l="player"+e.uniqueId;da=document.getElementById(l);if(!da){da=document.createElement("div");da.setAttribute("id",l);a.appendChild(da)}d(r,da,{js_onLoad:b.ref_id+".player.moogaloopLoaded",js_onThumbLoaded:b.ref_id+".player.moogaloopThumbLoaded"})}function g(){A&&A.api_pause()}function m(){if(X)B.loverInitiated();else A&&A.api_play()}function k(l){A&&A.api_seekTo(l.data)}function n(){A&&A.api_unload()}function f(l){o.embed.color=l.data;A&&A.api_changeColor(l.data)}function t(l){o.embed.loop=
!!l.data;A&&A.api_setLoop(o.embed.loop)}function E(l){if(A){l=l.data;if(o.embed.api.version<2)l*=100;A.api_setVolume(l)}}function u(l){var H=false;switch(l.name){case Fa:H=A?A.api_getCurrentTime().toFixed(3):0;break;case Ga:H=A?A.api_getDuration().toFixed(3):o.video.duration;break;case Wa:H=A?A.api_getVolume().toFixed(3):o.user.preferences.volume/100;break;case Pa:H=A?!!A.api_paused():true;break}h.sendBack(l.name,H)}function w(l){try{l.data=JSON.parse(l.data)}catch(H){}var K=o.embed.api.version<2?
l.data:"on"+l.data.ucfirst();if(A){A.api_addEventListener(l.data,b.ref_id+".player."+K);R.debug("Adding listener",l.data,b.ref_id+".player."+K)}else{R.debug("Queuing listener",l.data,b.ref_id+".player."+K);v.push(["addEventListener",l.data,b.ref_id+".player."+K])}}R.info("Options:",b);R.info("Config:",e.config);var B=this,o=e.config,D=e.ua,F=e.playerMode===kc?Mb:e.playerMode,h=e.api,p=h.events,y=b.swfs.cover[F],r=b.swfs.player[F+(FlashDetect.major>=10&&FlashDetect.minor>=2&&!D.linux?"_sv":"")],v=
[],s,P,da,X,A,J=(F===gb?"mobi":"mooga")+"loop"+(o.embed.on_site?"_local":"");B.config=o;R.info("swfUrl: ",r,"playerMode: ",F);o.embed.api.on&&p.bind(rb,g).bind(sb,m).bind(tb,k).bind(ub,n).bind(Va,f).bind(eb,t).bind(fb,E).bind(Fa,u).bind(Ga,u).bind(Wa,u).bind(Pa,u).bind(mc,w);B.onProgress=function(l){p.fire(ob,l.toFloat().toFixed(3))};B.onPlayProgress=function(l){p.fire(ob,{seconds:l.seconds.toFloat().toFixed(3),percent:l.percent.toFloat().toFixed(3),duration:l.duration.toFloat().toFixed(3)})};B.onLoading=
function(l){p.fire(nb,{bytes:l.bytesLoaded.toInt(),percent:l.percent.toFloat().toFixed(3)})};B.onLoadProgress=function(l){p.fire(nb,{percent:l.percent.toFloat().toFixed(3),bytesLoaded:l.bytesLoaded.toInt(),bytesTotal:l.bytesTotal.toInt(),duration:l.duration.toFloat().toFixed(3)})};B.onPlay=function(){p.fire(mb)};B.onPause=function(){p.fire(lb)};B.onSeek=function(l){p.fire(pb,o.embed.api.version<2?l.toFloat().toFixed(3):{seconds:l.seconds.toFloat().toFixed(3),percent:l.percent.toFloat().toFixed(3),
duration:l.duration.toFloat().toFixed(3)})};B.onFinish=function(){p.fire(Ab)};B.loverLoaded=function(){R.info("Lover loaded");$m.removeClass(a,Xa);X=document.getElementById("cover"+e.uniqueId);c();setTimeout(function(){if($m.hasClass(X,Z)){R.debug("Removing invisible from loaded timeout");B.loverThumbLoaded(true)}},Ic)};B.loverThumbLoaded=function(l){R.info("Lover thumbnail loaded?",l);if(!X){X=document.getElementById("cover"+e.uniqueId);c()}$m.removeClass(X,Z);$m.addClass(s,V)};B.loverInitiated=
function(){R.debug("Lover play button clicked");i()};B.moogaloopLoaded=function(){$m.removeClass(a,Xa);A=document.getElementById(b.ref_id);if(X){$m.remove(X);$m.removeClass(A,Z);X=null}else c();if(o.embed.api.on&&v.length>0)for(;v.length>0;){var l=v.shift(),H="api_"+l.shift();R.debug("Calling",H,"from queue",l);(new Function("this."+H+'("'+l.join('","')+'")')).call(A)}R.info("Welcome to Moogaloop!");setTimeout(function(){if($m.hasClass(A,Z)){R.debug("Removing invisible from loaded timeout");B.moogaloopThumbLoaded(true)}},
Ic)};B.moogaloopThumbLoaded=function(l){R.info("Moog thumbnail loaded?",l);A||(A=document.getElementById(b.ref_id));$m.removeClass(A,Z);$m.addClass(s,V)};B.destroy=function(){o.embed.api.on&&p.unbind(rb,g).unbind(sb,m).unbind(tb,k).unbind(ub,n).unbind(Va,f).unbind(eb,t).unbind(fb,E).unbind(Fa,u).unbind(Ga,u).unbind(Wa,u)};for(s=a.getElementsByTagName("div")[0];s.nextSibling;)a.removeChild(s.nextSibling);!(o.embed.on_site||o.embed.autoplay||o.embed.api.on||D.opera||F===gb||o.security.privacy==="password")?
j():i();a.parentNode.api_seekTo=function(l){k({data:l})}}});x.NoPlayer=MingClass.extend({init:function(a,b,e){function d(){var t=Math.round(a.clientWidth/2-g.clientWidth/2),E=Math.round(a.clientHeight/2-g.clientHeight/2);
g.style.left=t+"px";g.style.top=E+"px"}function c(){f.get(cssPath,function(t){n=t;j()})}function j(){var t,E=document.createElement("style");t=k.substring(k.indexOf("<style>"),k.indexOf("</style>")+8);n+=t.replace(/<(\/)?style>/g,"");k.replace(t,"");if(e.ua.ie){E.type="text/css";E.styleSheet.cssText=n}else E.appendChild(document.createTextNode(n));document.getElementsByTagName("head")[0].appendChild(E);g.innerHTML=k;if(script=g.getElementsByTagName("script")[0])setTimeout(function(){(new Function(script.innerHTML)).call(e.config)},
0);setTimeout(function(){i.show()},100)}var i=this,g=a.children[3],m=a.children[4],k,n,f=new XHR;htmlPath=b.html_path+"/ming_overlay_"+e.playerType+".html";cssPath=b.css_path;i.element=a;i.show=function(){var t=g.getElementsByTagName("div")[0];$m.removeClass(g,V);$m.removeClass(m,V);d();setTimeout(function(){$m.addClass(t,Xb);$m.addClass(a,ua)},10)};for(window.addEventListener?window.addEventListener("resize",d,false):window.attachEvent("onresize",d);g.previousSibling;){if(g.previousSibling.className===
ac)break;a.removeChild(g.previousSibling)}$m.removeClass(a,Xa);(function(){f.get(htmlPath+"?"+(new Date).getTime(),function(t){k=t;c()})})()}});x.API=MingClass.extend({init:function(a){function b(o){if(!o||o==="")return false;try{return JSON.parse(o)}catch(D){var F={},h,p,y;o.split("&").forEach(function(r){h=r.split("=");p=decodeURIComponent(h[0]);y=decodeURIComponent(h[1]);if(p!=="id"){if(p==="params")p="value";if(y.contains(","))y=y.split(",")[0];F[p]=y}});return F}}function e(o){if($m.type(o)!=="string"){o=(o=o)||{};if(n)o.player_id=n;o.data==="undefined"&&delete o.data;
if(k>1&&window.JSON)o=JSON.stringify(o);else{var D="method="+encodeURIComponent(o.method||o.event)+"&params=",F=[];if(o.value)F.push(encodeURIComponent(o.value));else if($m.type(o.data)==="object")for(var h in o.data)F.push(encodeURIComponent(o.data[h]));else o.data&&o.data!=="undefined"&&F.push(encodeURIComponent(o.data));o.player_id&&F.push(o.player_id);o=D+F.join(",")}}window.parent.postMessage(o,g);R.debug("<- Sent",o)}function d(o){var D=o.name,F=o.data;try{F=JSON.parse(o.data)}catch(h){}if(k<
2){D=$m.findKey(D,t);switch(D){case "onSeek":case "onProgress":F.percent&&delete F.percent;case "onLoading":F.duration&&delete F.duration;break}}if(m[D]===true||o.name===vb)e({event:D,data:F})}function c(o){var D=b(o.data);o=D.method;var F=D.value;if(!D||!o)return false;if(o.substr(0,4)==="api_"){o=o.substr(4);o=w[o]||o;o=o.replace("()","")}D=o+"()";if(D===mc){m[F]=true;B.fire(mc,F);R.debug("-> Now listening for",F)}else if(D===vc){m[F]=false;B.fire(vc,F);R.debug("-> Stop listening for",F)}else if(E.contains(D)){R.debug("-> Received",
o,F);switch(D){case fb:F=F.toFloat();if(k<2)F/=100;break;case eb:F=!!F.toInt();break;case Va:if(F.search(/^[A-Fa-f\d]+$/g)===-1||F.length!==3&&F.length!==6){R.warn("Invalid color value");return}break}B.fire(D,F)}else if(u.contains(D)){R.debug("-> Received request for",o,F);B.fire(D,F)}}function j(o){var D=false;switch(o.name){case wc:D=a.embed.color;break;case xc:D=a.video.url;break;case yc:D=a.video.embed_code;break}i.sendBack(o.name,D)}if(!a.embed.api.on){this.events=new EventManager;return false}if(!window.postMessage||
!window.parent.postMessage||window.location===window.parent.location){R.warn("Player API unavailable because this browser does not support postMessage or is not loaded in an iframe.");a.embed.api.on=0;this.events=new EventManager;return false}var i=this,g=decodeURIComponent(a.request.referrer),m={},k=a.embed.api.version,n=a.embed.api.player_id,f=[nb,ob,mb,lb,Ab,pb,vb,hd],t={onFinish:Ab,onLoading:nb,onLoad:vb,onProgress:ob,onPlay:mb,onPause:lb,onSeek:pb},E=[mc,vc,sb,rb,Va,tb,eb,fb,ub],u=[Ga,Fa,Wa,
wc,Cb,xc,yc,ab,bb,Pa],w={changeColor:Va},B=new EventManager;i.events=B;i.sendBack=function(o,D){o=o.replace("()","");if(k<2)o="api_"+o;e({method:o,value:D})};i.sendError=function(){R.error("API error")};i.destroy=function(){window.removeEventListener?window.removeEventListener("message",c,false):window.detachEvent("onmessage",c)};f.forEach(function(o){B.bind(o,d)});B.bind(wc,j).bind(xc,j).bind(yc,j);window.addEventListener?window.addEventListener("message",c,false):window.attachEvent("onmessage",
c)}});x.Stats=MingClass.extend({init:function(a,b){var e=b.playerType.ucfirst()+" "+b.playerMode.ucfirst(),d=window._gaq||[],c=null,j=b.playerType===yb?"local":"",i=(b.playerType===yb?"html5_"+b.playerMode:b.playerMode===gb?"mobiloop":"moogaloop")+
"_"+(a.embed.on_site?j:"embed");d.push(["pt._setAccount",a.analytics.ga_account]);this.clientLog=function(){var g=new XHR,m="//"+a.request.player_url+"/log/client",k=["request_signature="+a.request.signature,"video="+ICanHas.video,"h264="+ICanHas.video.h264,"vp8="+ICanHas.video.vp8,"vp6="+ICanHas.video.vp6,"flash="+FlashDetect.version,"touch="+ICanHas.touch,"screen_width="+screen.width,"screen_height="+screen.height].join("&");g.post(m,k,function(){})};this.googleLog=function(g,m){m=parseInt(Number(m),
10);if(isNaN(m))m=undefined;R.log("google analytics:",e,g,a.video.id,m);d.push(["pt._trackEvent",e,g,a.video.id+"",m])};this.partialPlayLog=function(g,m,k){g=parseInt(g,10);if(g>c){var n=new XHR,f="//"+a.request.player_url+"/log/partial";m="request_signature="+a.request.signature+"&seconds="+g+"&quality="+m;R.log("vimeo stats:",g,"seconds played");k?n.post(f,m):n.post(f,m,function(){});c=g}};this.vimeoLog=function(g,m,k,n){var f=new XHR,t="//"+a.request.player_url+"/log/"+g+"/"+a.video.id,E="?embed_location="+
a.request.referrer+"&request_signature="+a.request.signature;E+="&type="+i;if(m)E+="&quality="+m;if(k)E+="&percent="+k;R.log("vimeo stats:",g,m,k);n?f.post(t,E):f.post(t,E,function(){})}}});if(!x.UI)x.UI={};x.UI.CanvasElement=MingClass.extend({init:function(a){if(!a)return false;this.element=a;this.origWidth=a.getAttribute("width");this.origHeight=
a.getAttribute("height");this.width=this.origWidth*Hb;this.height=this.origHeight*Hb},draw:function(a,b,e,d,c){this.setData(a).setTranslation(b).setScale(e).setColor(d).setShadow(c);this.refresh();return this},setData:function(a){this.data=a;return this},setTranslation:function(a){this.translation=a;return this},setScale:function(a){this.scale=a;return this},setColor:function(a){this.color=a;return this},setShadow:function(a){this.shadow=a;return this},refresh:function(){var a=this.data,b=this.shadow;
try{if(!a||!this.element.getContext)return false}catch(e){return false}var d=this.scale||1,c=this.translation?$m.clone(this.translation):{x:0,y:0},j=this.color||"ffffff";this.element.attr({width:this.width,height:this.height});d*=Hb;c.x*=Hb;c.y*=Hb;var i=this.element.getContext("2d"),g;i.clearRect(0,0,this.width,this.height);i.save();i.translate(c.x,c.y);i.scale(d,d);i.fillStyle=i.strokeStyle="#"+j;if(b){i.shadowOffsetX=i.shadowOffsetY=0;i.shadowBlur=10*Hb;i.shadowColor="rgba(0,0,0,0.5)"}d=0;for(c=
a.length;d<c;d++)for(g in a[d])if(b=a[d][g])if($m.isArray(b))i[g].apply(i,b);else i[g]=b;else i[g].apply(i);i.restore();return this}});x.ContextMenu=MingClass.extend({init:function(a,b,e){function d(f){(f.target.hasAncestor?!f.target.hasAncestor(g):true)&&!c.isHidden&&c.hide()}
var c=this,j=window,i=document,g=document.createElement("div"),m=[],k=!!e.win,n=!!e.mac;c.element=g;c.items=m;c.isHidden=true;c.add=function(f,t){var E=new x.ContextMenu.Item(f,c);t||(t=g);t.appendChild(E.element);m.push(E);f.type=="info"&&t.addClass(Yc)};c.remove=function(f){m.slice(f,1)};c.show=function(){c.refresh();var f=event.pageX,t=event.pageY,E=i.width,u=i.height;if(f+g.clientWidth>E)f=E-g.clientWidth-5;if(t+g.clientHeight>u)t=u-g.clientHeight-5;g.attr("style","left: "+f+"px; top: "+t+"px;");
g.removeClass(Z);c.isHidden=false};c.hide=function(){g.addClass(Z);c.isHidden=true};j.addEventListener("contextmenu",d,false);j.addEventListener("contextmenu",function(f){if(!(k?f&&f.ctrlKey:f&&f.metaKey)&&f.target.hasAncestor(a)){c.show();if(f.returnValue)f.returnValue=false;else if(f.preventDefault)f.preventDefault();else return false}else c.isHidden||c.hide()},false);j.addEventListener("click",d,false);j.addEventListener("blur",d,false);j.addEventListener("mousedown",function(f){var t=f.target.hasAncestor?
!f.target.hasAncestor(a):false,E=n?f&&f.metaKey:f&&f.ctrlKey;if(!c.isHidden||f&&f.button>0&&!t&&!E){f.stopPropagation&&f.stopPropagation();f.preventDefault&&f.preventDefault();f.preventCapture&&f.preventCapture()}j.focus()},false);b&&c.setData(b).refresh();g.addClass(zd);c.hide();i.getElementsByTagName("body")[0].appendChild(g)},setData:function(a){this.data=a;return this},refresh:function(){function a(){var i=document.createElement("ul");d.appendChild(i);i.addClass("index"+j);j++;return i}function b(i,
g){i.forEach(function(m){if($m.isArray(m)){c=c.children.length==0?c:a();b(m,c)}else e.add(m,g)})}var e=this,d=e.element,c,j=0;e.element.innerHTML="";c=a();b(e.data,c);return this}});x.ContextMenu.Item=MingClass.extend({init:function(a,b){this.element=document.createElement("li");this.controller=b;a&&this.setData(a).refresh()},setData:function(a){this.data=a;return this},refresh:function(){function a(){i.addClass(Xc);i.addEventListener("click",function(){window.open(c.url)},false)}function b(){i.addClass(Bc);
i.innerHTML="<span>"+i.innerHTML+"</span>";var g=$m.type(c.active)==="function"?c.active.call():c.active;g&&i.addClass(ib);i.addEventListener("click",function(){(g=$m.type(c.active)==="function"?c.active.call():!c.active)?i.addClass(ib):i.removeClass(ib)},false)}function e(){i.addClass(Xc);i.addEventListener("click",function(){var g=Array.prototype.slice.call(arguments);j=="toggle"&&g.push(c.active);d.controller.hide();c.action.apply(this,g)},false)}var d=this,c=d.data,j=d.data.type,i=d.element;i.innerHTML=
$m.type(c.text)==="function"?c.text.call():c.text;if(j=="toggle")b();else if(j=="link")a();else j=="info"&&i.addClass(Yc);c.action&&e();return d}});